[package]
name = "kse"
version = "0.1.0"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]

[dependencies]
num-traits  = { git = "http://github.com/rust-num/num" }
num-complex = { git = "http://github.com/rust-num/num" }
itertools = "*"
ndarray = "0.8"
ndarray-linalg = { git = "http://github.com/termoshtt/ndarray-linalg" }
ndarray-odeint = { git = "http://github.com/termoshtt/ndarray-odeint" }
fftw = { git = "http://github.com/termoshtt/rust-fftw3" }
